apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-config
  namespace: ims
data:
  DB_HOST: "mysql-service"
  DB_NAME: "ims"
  DB_USER: "raju"
  NODE_ENV: "production"
  FRONTEND_URL: "http://localhost" # Adjust based on actual K8s ingress/LoadBalancer
