apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: ims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ims-server:latest # Ensure image is build and available in K8s node
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ims-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ims-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: ims-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ims-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ims-secrets
              key: JWT_SECRET
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: ims-secrets
              key: COOKIE_SECRET
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: ims-config
              key: FRONTEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: ims
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
